/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AkoToFungujeRouteImport } from './routes/ako-to-funguje'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as ObchodnePodmienkyRouteImport } from './routes/obchodne-podmienky'
import { Route as ObnovitHesloRouteImport } from './routes/obnovit-heslo'
import { Route as PonukaSluziebRouteImport } from './routes/ponuka-sluzieb'
import { Route as PrePoskytovatelovRouteImport } from './routes/pre-poskytovatelov'
import { Route as PridajSluzbuRouteImport } from './routes/pridaj-sluzbu'
import { Route as PrihlasenieRouteImport } from './routes/prihlasenie'
import { Route as RegistraciaRouteImport } from './routes/registracia'
import { Route as VytvoritPoziadavkuRouteImport } from './routes/vytvorit-poziadavku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkoToFungujeRoute = AkoToFungujeRouteImport.update({
  id: '/ako-to-funguje',
  path: '/ako-to-funguje',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodnePodmienkyRoute = ObchodnePodmienkyRouteImport.update({
  id: '/obchodne-podmienky',
  path: '/obchodne-podmienky',
  getParentRoute: () => rootRouteImport,
} as any)
const ObnovitHesloRoute = ObnovitHesloRouteImport.update({
  id: '/obnovit-heslo',
  path: '/obnovit-heslo',
  getParentRoute: () => rootRouteImport,
} as any)
const PonukaSluziebRoute = PonukaSluziebRouteImport.update({
  id: '/ponuka-sluzieb',
  path: '/ponuka-sluzieb',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePoskytovatelovRoute = PrePoskytovatelovRouteImport.update({
  id: '/pre-poskytovatelov',
  path: '/pre-poskytovatelov',
  getParentRoute: () => rootRouteImport,
} as any)
const PridajSluzbuRoute = PridajSluzbuRouteImport.update({
  id: '/pridaj-sluzbu',
  path: '/pridaj-sluzbu',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlasenieRoute = PrihlasenieRouteImport.update({
  id: '/prihlasenie',
  path: '/prihlasenie',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraciaRoute = RegistraciaRouteImport.update({
  id: '/registracia',
  path: '/registracia',
  getParentRoute: () => rootRouteImport,
} as any)
const VytvoritPoziadavkuRoute = VytvoritPoziadavkuRouteImport.update({
  id: '/vytvorit-poziadavku',
  path: '/vytvorit-poziadavku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/blog': typeof BlogRoute
  '/o-nas': typeof ONasRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/obnovit-heslo': typeof ObnovitHesloRoute
  '/ponuka-sluzieb': typeof PonukaSluziebRoute
  '/pre-poskytovatelov': typeof PrePoskytovatelovRoute
  '/pridaj-sluzbu': typeof PridajSluzbuRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
  '/vytvorit-poziadavku': typeof VytvoritPoziadavkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/blog': typeof BlogRoute
  '/o-nas': typeof ONasRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/obnovit-heslo': typeof ObnovitHesloRoute
  '/ponuka-sluzieb': typeof PonukaSluziebRoute
  '/pre-poskytovatelov': typeof PrePoskytovatelovRoute
  '/pridaj-sluzbu': typeof PridajSluzbuRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
  '/vytvorit-poziadavku': typeof VytvoritPoziadavkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/blog': typeof BlogRoute
  '/o-nas': typeof ONasRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/obnovit-heslo': typeof ObnovitHesloRoute
  '/ponuka-sluzieb': typeof PonukaSluziebRoute
  '/pre-poskytovatelov': typeof PrePoskytovatelovRoute
  '/pridaj-sluzbu': typeof PridajSluzbuRoute
  '/prihlasenie': typeof PrihlasenieRoute
  '/registracia': typeof RegistraciaRoute
  '/vytvorit-poziadavku': typeof VytvoritPoziadavkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ako-to-funguje'
    | '/blog'
    | '/o-nas'
    | '/obchodne-podmienky'
    | '/obnovit-heslo'
    | '/ponuka-sluzieb'
    | '/pre-poskytovatelov'
    | '/pridaj-sluzbu'
    | '/prihlasenie'
    | '/registracia'
    | '/vytvorit-poziadavku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ako-to-funguje'
    | '/blog'
    | '/o-nas'
    | '/obchodne-podmienky'
    | '/obnovit-heslo'
    | '/ponuka-sluzieb'
    | '/pre-poskytovatelov'
    | '/pridaj-sluzbu'
    | '/prihlasenie'
    | '/registracia'
    | '/vytvorit-poziadavku'
  id:
    | '__root__'
    | '/'
    | '/ako-to-funguje'
    | '/blog'
    | '/o-nas'
    | '/obchodne-podmienky'
    | '/obnovit-heslo'
    | '/ponuka-sluzieb'
    | '/pre-poskytovatelov'
    | '/pridaj-sluzbu'
    | '/prihlasenie'
    | '/registracia'
    | '/vytvorit-poziadavku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkoToFungujeRoute: typeof AkoToFungujeRoute
  BlogRoute: typeof BlogRoute
  ONasRoute: typeof ONasRoute
  ObchodnePodmienkyRoute: typeof ObchodnePodmienkyRoute
  ObnovitHesloRoute: typeof ObnovitHesloRoute
  PonukaSluziebRoute: typeof PonukaSluziebRoute
  PrePoskytovatelovRoute: typeof PrePoskytovatelovRoute
  PridajSluzbuRoute: typeof PridajSluzbuRoute
  PrihlasenieRoute: typeof PrihlasenieRoute
  RegistraciaRoute: typeof RegistraciaRoute
  VytvoritPoziadavkuRoute: typeof VytvoritPoziadavkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ako-to-funguje': {
      id: '/ako-to-funguje'
      path: '/ako-to-funguje'
      fullPath: '/ako-to-funguje'
      preLoaderRoute: typeof AkoToFungujeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodne-podmienky': {
      id: '/obchodne-podmienky'
      path: '/obchodne-podmienky'
      fullPath: '/obchodne-podmienky'
      preLoaderRoute: typeof ObchodnePodmienkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obnovit-heslo': {
      id: '/obnovit-heslo'
      path: '/obnovit-heslo'
      fullPath: '/obnovit-heslo'
      preLoaderRoute: typeof ObnovitHesloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponuka-sluzieb': {
      id: '/ponuka-sluzieb'
      path: '/ponuka-sluzieb'
      fullPath: '/ponuka-sluzieb'
      preLoaderRoute: typeof PonukaSluziebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-poskytovatelov': {
      id: '/pre-poskytovatelov'
      path: '/pre-poskytovatelov'
      fullPath: '/pre-poskytovatelov'
      preLoaderRoute: typeof PrePoskytovatelovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pridaj-sluzbu': {
      id: '/pridaj-sluzbu'
      path: '/pridaj-sluzbu'
      fullPath: '/pridaj-sluzbu'
      preLoaderRoute: typeof PridajSluzbuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlasenie': {
      id: '/prihlasenie'
      path: '/prihlasenie'
      fullPath: '/prihlasenie'
      preLoaderRoute: typeof PrihlasenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registracia': {
      id: '/registracia'
      path: '/registracia'
      fullPath: '/registracia'
      preLoaderRoute: typeof RegistraciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vytvorit-poziadavku': {
      id: '/vytvorit-poziadavku'
      path: '/vytvorit-poziadavku'
      fullPath: '/vytvorit-poziadavku'
      preLoaderRoute: typeof VytvoritPoziadavkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkoToFungujeRoute: AkoToFungujeRoute,
  BlogRoute: BlogRoute,
  ONasRoute: ONasRoute,
  ObchodnePodmienkyRoute: ObchodnePodmienkyRoute,
  ObnovitHesloRoute: ObnovitHesloRoute,
  PonukaSluziebRoute: PonukaSluziebRoute,
  PrePoskytovatelovRoute: PrePoskytovatelovRoute,
  PridajSluzbuRoute: PridajSluzbuRoute,
  PrihlasenieRoute: PrihlasenieRoute,
  RegistraciaRoute: RegistraciaRoute,
  VytvoritPoziadavkuRoute: VytvoritPoziadavkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
